jenkins:
  systemMessage: "reading casc config from raw url"
jobs:
  - script: >
      pipelineJob('Jenkins Job Builder') { 
        definition { 
          cpsScm { 
            scm { 
              git { 
                remote { url('git://github.com/tizianatroukens/jenkins-kubernetes.git') } 
                branches('master') 
                scriptPath('Jenkinsfile')
              }
            }
          }
        }
      }
unclassified:
  location:
    url: ${JENKINS_URL}