jenkins:
  systemMessage: "reading casc config from raw url"
jobs:
  - script: >
      pipelineJob('Jenkins Job Builder') { 
        definition { 
          cpsScm { 
            scm { 
              git { 
                remote { url('git@github.com:tizianatroukens/jenkins-kubernetes.git') } 
                branches('master') 
                scriptPath('Jenkinsfile')
              }
            }
          }
        }
      }
unclassified:
  location:
    url: "http://192.168.99.100:32000"
credentials:
  system:
    domainCredentials:
      - credentials:
          - certificate:
              scope: SYSTEM
              id: ssh_private_key
              keyStoreSource:
                fileOnMaster:
                  keyStoreFile: /var/jenkins_home/.ssh/id_rsa