apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins-project
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "added job from casc"
    jobs:
      - script: >
          pipelineJob('Jenkins Job Builder') { 
            definition { 
              cpsScm { 
                scm { 
                  git { 
                    remote { url('git@github.com:tizianatroukens/jenkins-kubernetes.git') } 
                    branches('master') 
                    scriptPath('Jenkinsfile')
                  }
                }
              }
            }
          }
    unclassified:
      location:
        url: "http://192.168.99.100:32000"