jenkins:
  systemMessage: "reading casc config from raw url"
jobs:
  - script: >
      pipelineJob('Jenkins Job Builder') { 
        definition { 
          cpsScm { 
            scm { 
              git { 
                remote { 
                  name('GitHub-Kubernetes')
                  url('git@github.com:tizianatroukens/jenkins-kubernetes.git')
                  credentials('ssh_github')
                } 
                branches('master') 
                scriptPath('Jenkinsfile')
              }
            }
          }
        }
      }
unclassified:
  location:
    url: ${JENKINS_URL}
credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: SYSTEM
              id: ssh_github
              username: git
              description: "SSH key for GitHub"
              privateKeySource:
                directEntry:
                  privateKey: ${SSH_PRIVATE_KEY}