plugins:
  sites:
  - id: "default"
    url: "https://updates.jenkins.io/update-center.json"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-agent:50000"
      jenkinsUrl: "http://jenkins:8080"
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      namespace: "jenkins-project"
      serverUrl: "https://kubernetes.default"
      templates:
      - containers:
        - args: "${computer.jnlpmac} ${computer.name}"
          envVars:
          - containerEnvVar:
              key: "JENKINS_URL"
              value: "http://jenkins:8080"
          image: "jenkins/jnlp-slave:3.10-1"
          name: "jnlp"
          resourceLimitCpu: "200m"
          resourceLimitMemory: "256Mi"
          resourceRequestCpu: "200m"
          resourceRequestMemory: "256Mi"
        label: "jenkins-jenkins-slave "
        name: "default"
        nodeUsageMode: "NORMAL"
        slaveConnectTimeoutStr: "0"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  systemMessage: "CASC Jenkins playing"
  views:
  - all:
      name: "all"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
